### ISSUE TITLE
Failed to load dynamic library 'serialport.dll'

### ISSUE THREAD

**Issue by HimorriveL** [jpnurmi/libserialport.dart#48]
I`m try use, but I have a error:
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Invalid argument(s): Failed to load dynamic library 'serialport.dll': error code 1792009544
#0      Perifericos.pesoBalancaUranoUDC (package:my_app_splash/utils/perifericos/perifericos.dart:11:7)
<asynchronous suspension>`

`dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.4.1
  window_manager:
    git:
      url: https://github.com/leanflutter/window_manager.git
      ref: main
  printing: ^5.6.3
  mask_text_input_formatter: ^2.0.0
  path_provider: ^2.0.7
  libserialport: ^0.2.0+3`

**Comment by jpnurmi** [comment]
Please read the README.

> This package uses [dart:ffi](https://dart.dev/guides/libraries/c-interop) to call `libserialport`'s C APIs, which implies that `libserialport` must be bundled to or deployed with the host application. It can be tedious to build and deploy `libserialport` on all target platforms, but in case you are building a Flutter app instead of a pure Dart app, there is a ready-made drop-in solution called [`flutter_libserialport`](https://pub.dev/packages/flutter_libserialport) that utilizes Flutter's build system to build and deploy `libserialport` on all supported platforms:

**Comment by HimorriveL** [comment]
I have to add flutter_libserialport too?
