### ISSUE TITLE
Please upgrade dependency on "ffi" to 2.0.x

### ISSUE THREAD

**Issue by eximius313** [jpnurmi/libserialport.dart#59]
FFI is [currently](https://pub.dev/packages/ffi) in version 2.0.1, while `libserialport` [depends on 1.0.0](https://github.com/jpnurmi/libserialport.dart/blob/main/pubspec.yaml), which prevents users from using other libraries.
Could you please upgrade ffi to 2.0.x?

**Comment by Dsthdragon** [comment]
Any hope on this getting done?

**Comment by Dsthdragon** [comment]
so am trying to update the libserialport on my fork but cant seem to get the busy test to pass
https://github.com/Dsthdragon/libserialport.dart

**Comment by jpnurmi** [comment]
Thanks, @Dsthdragon! https://github.com/jpnurmi/libserialport.dart/pull/62

**Comment by eximius313** [comment]
Awesome!
Thanks so much @Dsthdragon !

@jpnurmi, are you planning to release new version?

**Comment by jpnurmi** [comment]
v0.3.0 released: https://pub.dev/packages/libserialport/versions/0.3.0
